In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv('FlowStatsfile.csv')
df2=pd.read_csv('icmp.csv')
df3=pd.read_csv('tcp.csv')
df4=pd.read_csv('udp.csv')
df5=pd.read_csv('land.csv')

In [54]:
df1['label']=df1['label'].replace(1,0)

In [3]:
df1.head()

,timestamp,datapath_id,flow_id,ip_src,tp_src,ip_dst,tp_dst,ip_proto,icmp_code,icmp_type,...,idle_timeout,hard_timeout,flags,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond,label
0,1.705819e+09,3,10.0.0.294575310.0.0.1505117,10.0.0.29,45753,10.0.0.1,5051,17,-1,-1,...,14,94,0,2512,3798144,418.666667,0.000004,633024.0,0.006097,0
1,1.705819e+09,9,10.0.0.294575310.0.0.1505117,10.0.0.29,45753,10.0.0.1,5051,17,-1,-1,...,13,93,0,41842,63265104,5977.428571,0.000078,9037872.0,0.118253,0
2,1.705819e+09,4,10.0.0.294575310.0.0.1505117,10.0.0.29,45753,10.0.0.1,5051,17,-1,-1,...,14,94,0,2501,3781512,416.833333,0.000006,630252.0,0.009721,0
3,1.705819e+09,1,10.0.0.294575310.0.0.1505117,10.0.0.29,45753,10.0.0.1,5051,17,-1,-1,...,14,94,0,2480,3749760,413.333333,0.000030,624960.0,0.045729,0
4,1.705819e+09,11,10.0.0.294575310.0.0.1505117,10.0.0.29,45753,10.0.0.1,5051,17,-1,-1,...,14,94,0,2518,3807216,419.666667,0.000003,634536.0,0.004254,0

In [10]:
df2.head()

,timestamp,datapath_id,flow_id,ip_src,tp_src,ip_dst,tp_dst,ip_proto,icmp_code,icmp_type,...,idle_timeout,hard_timeout,flags,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond,label
0,1.705333e+09,4,1.17.10.10010.0.0.1101,1.17.10.10,0,10.0.0.11,0,1,0,8,...,16,96,0,0,0,0.0,0.0,0.0,0.0,1
1,1.705333e+09,4,1.253.175.69010.0.0.1101,1.253.175.69,0,10.0.0.11,0,1,0,8,...,16,96,0,0,0,0.0,0.0,0.0,0.0,1
2,1.705333e+09,4,10.100.162.124010.0.0.1101,10.100.162.124,0,10.0.0.11,0,1,0,8,...,15,95,0,0,0,0.0,0.0,0.0,0.0,1
3,1.705333e+09,4,10.107.190.144010.0.0.1101,10.107.190.144,0,10.0.0.11,0,1,0,8,...,16,96,0,0,0,0.0,0.0,0.0,0.0,1
4,1.705333e+09,4,10.146.56.13010.0.0.1101,10.146.56.13,0,10.0.0.11,0,1,0,8,...,16,96,0,0,0,0.0,0.0,0.0,0.0,1

In [11]:
df3.head()

,timestamp,datapath_id,flow_id,ip_src,tp_src,ip_dst,tp_dst,ip_proto,icmp_code,icmp_type,...,idle_timeout,hard_timeout,flags,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond,label
0,1.705335e+09,3,0.13.254.55276310.0.0.9806,0.13.254.55,2763,10.0.0.9,80,6,-1,-1,...,15,95,0,0,0,0.0,0.0,0.0,0.0,1
1,1.705335e+09,3,1.52.38.70285210.0.0.9806,1.52.38.70,2852,10.0.0.9,80,6,-1,-1,...,15,95,0,0,0,0.0,0.0,0.0,0.0,1
2,1.705335e+09,3,101.212.30.199280210.0.0.9806,101.212.30.199,2802,10.0.0.9,80,6,-1,-1,...,15,95,0,0,0,0.0,0.0,0.0,0.0,1
3,1.705335e+09,3,101.22.5.37294110.0.0.9806,101.22.5.37,2941,10.0.0.9,80,6,-1,-1,...,16,96,0,0,0,0.0,0.0,0.0,0.0,1
4,1.705335e+09,3,101.30.70.105315910.0.0.9806,101.30.70.105,3159,10.0.0.9,80,6,-1,-1,...,15,95,0,0,0,0.0,0.0,0.0,0.0,1

In [12]:
df4.head()

,timestamp,datapath_id,flow_id,ip_src,tp_src,ip_dst,tp_dst,ip_proto,icmp_code,icmp_type,...,idle_timeout,hard_timeout,flags,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond,label
0,1.705335e+09,6,10.0.0.1010.0.0.1601,10.0.0.1,0,10.0.0.16,0,1,0,8,...,14,94,0,0,0,0.0,0.0,0.0,0.0,1
1,1.705335e+09,6,10.0.0.1010.0.0.1601,10.0.0.1,0,10.0.0.16,0,1,0,0,...,18,98,0,0,0,0.0,0.0,0.0,0.0,1
2,1.705335e+09,6,10.0.0.1010.0.0.1701,10.0.0.1,0,10.0.0.17,0,1,0,8,...,14,94,0,0,0,0.0,0.0,0.0,0.0,1
3,1.705335e+09,6,10.0.0.1010.0.0.1701,10.0.0.1,0,10.0.0.17,0,1,0,0,...,19,99,0,0,0,0.0,0.0,0.0,0.0,1
4,1.705335e+09,6,10.0.0.1010.0.0.1801,10.0.0.1,0,10.0.0.18,0,1,0,8,...,14,94,0,0,0,0.0,0.0,0.0,0.0,1

In [13]:
df5.head()

,timestamp,datapath_id,flow_id,ip_src,tp_src,ip_dst,tp_dst,ip_proto,icmp_code,icmp_type,...,idle_timeout,hard_timeout,flags,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond,label
0,1.705336e+09,2,10.0.0.4010.0.0.401,10.0.0.4,0,10.0.0.4,0,1,0,8,...,20,100,0,404707,65562534,0.000000,0.000000,0.000000e+00,0.000000,1
1,1.705336e+09,1,10.0.0.4010.0.0.401,10.0.0.4,0,10.0.0.4,0,1,0,8,...,16,96,0,411823,66715326,102955.750000,0.000551,1.667883e+07,0.089192,1
2,1.705336e+09,4,10.0.0.11010.0.0.1101,10.0.0.11,0,10.0.0.11,0,1,0,8,...,15,95,0,542439,87875118,108487.800000,0.001930,1.757502e+07,0.312723,1
3,1.705336e+09,2,10.0.0.4010.0.0.401,10.0.0.4,0,10.0.0.4,0,1,0,8,...,11,91,0,743180,120395160,82575.555556,0.000797,1.337724e+07,0.129041,1
4,1.705336e+09,1,10.0.0.4010.0.0.401,10.0.0.4,0,10.0.0.4,0,1,0,8,...,6,86,0,750297,121548114,53592.642857,0.001010,8.682008e+06,0.163591,1

In [4]:
print(len(df1),len(df2),len(df3),len(df4),len(df5))

50359 116160 18440 199952 1061

In [5]:

df=pd.concat([df1,df2,df3,df4,df5],axis=0)

In [6]:
df.head()

,timestamp,datapath_id,flow_id,ip_src,tp_src,ip_dst,tp_dst,ip_proto,icmp_code,icmp_type,...,idle_timeout,hard_timeout,flags,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond,label
0,1.705819e+09,3,10.0.0.294575310.0.0.1505117,10.0.0.29,45753,10.0.0.1,5051,17,-1,-1,...,14,94,0,2512,3798144,418.666667,0.000004,633024.0,0.006097,0
1,1.705819e+09,9,10.0.0.294575310.0.0.1505117,10.0.0.29,45753,10.0.0.1,5051,17,-1,-1,...,13,93,0,41842,63265104,5977.428571,0.000078,9037872.0,0.118253,0
2,1.705819e+09,4,10.0.0.294575310.0.0.1505117,10.0.0.29,45753,10.0.0.1,5051,17,-1,-1,...,14,94,0,2501,3781512,416.833333,0.000006,630252.0,0.009721,0
3,1.705819e+09,1,10.0.0.294575310.0.0.1505117,10.0.0.29,45753,10.0.0.1,5051,17,-1,-1,...,14,94,0,2480,3749760,413.333333,0.000030,624960.0,0.045729,0
4,1.705819e+09,11,10.0.0.294575310.0.0.1505117,10.0.0.29,45753,10.0.0.1,5051,17,-1,-1,...,14,94,0,2518,3807216,419.666667,0.000003,634536.0,0.004254,0

In [7]:
df['label'].value_counts()

label
1    335613
0     50359
Name: count, dtype: int64

In [35]:
!pip install imblearn

Defaulting to user installation because normal site-packages is not writeable
Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Collecting imbalanced-learn (from imblearn)
  Downloading imbalanced_learn-0.11.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: numpy>=1.17.3 in /home/ark/.local/lib/python3.10/site-packages (from imbalanced-learn->imblearn) (1.26.0)
Requirement already satisfied: scipy>=1.5.0 in /usr/lib/python3/dist-packages (from imbalanced-learn->imblearn) (1.8.0)
Requirement already satisfied: scikit-learn>=1.0.2 in /home/ark/.local/lib/python3.10/site-packages (from imbalanced-learn->imblearn) (1.3.2)
Requirement already satisfied: joblib>=1.1.1 in /home/ark/.local/lib/python3.10/site-packages (from imbalanced-learn->imblearn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/ark/.local/lib/python3.10/site-packages (from imbalanced-learn->imblearn) (3.2.0)
Downloading imbalanced_learn-0.11.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.6/235.6 kB 1.9 MB/s eta 0:00:00a 0:00:01
DEPRECATION: distro-info 1.1build1 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
DEPRECATION: python-debian 0.1.43ubuntu1 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of python-debian or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: imbalanced-learn, imblearn
Successfully installed imbalanced-learn-0.11.0 imblearn-0.0

In [9]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, accuracy_score
from imblearn.under_sampling import RandomUnderSampler
from sklearn.ensemble import RandomForestClassifier

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [10]:


df.iloc[:, 2] = df.iloc[:, 2].str.replace('.', '')
df.iloc[:, 3] = df.iloc[:, 3].str.replace('.', '')
df.iloc[:, 5] = df.iloc[:, 5].str.replace('.', '')

X_flow = df.iloc[:, :-1].values
X_flow = X_flow.astype('float64')

y_flow = df.iloc[:, -1].values

X_flow_train, X_flow_test, y_flow_train, y_flow_test = train_test_split(X_flow, y_flow, test_size=0.25, random_state=0)

In [11]:
rus = RandomUnderSampler(random_state=42)

# Split data into train/test sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  

# Fit random under-sampler on training data
X_train_rus, y_train_rus = rus.fit_resample(X_flow_train, y_flow_train)

# Instantiate model  
rf = RandomForestClassifier()  

# Train model on balanced dataset
rf.fit(X_train_rus, y_train_rus)   

# Predict on test data
y_pred = rf.predict(X_flow_test)  

# Evaluate F1 and accuracy
f1 = f1_score(y_flow_test, y_pred)
acc = accuracy_score(y_flow_test, y_pred)

print('F1 score:', f1)
print('Accuracy score:', acc)

F1 score: 1.0
Accuracy score: 1.0

In [ ]:
print(len())

In [51]:
df.head()

,timestamp,datapath_id,flow_id,ip_src,tp_src,ip_dst,tp_dst,ip_proto,icmp_code,icmp_type,...,idle_timeout,hard_timeout,flags,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond,label
0,1.705328e+09,2,100015050100010365226,10001,5050,100010,36522,6,-1,-1,...,17,97,0,507,33490,169.000000,1.748276e-05,11163.333333,1.154828e-03,0
1,1.705328e+09,2,1000180100010352586,10001,80,100010,35258,6,-1,-1,...,17,97,0,5,936,1.666667,1.724138e-07,312.000000,3.227586e-05,0
2,1.705328e+09,2,1000180100010473546,10001,80,100010,47354,6,-1,-1,...,18,98,0,4,629,2.000000,4.032258e-09,314.500000,6.340726e-07,0
3,1.705328e+09,2,10001505010006435766,10001,5050,10006,43576,6,-1,-1,...,20,100,0,175,11590,0.000000,0.000000e+00,0.000000,0.000000e+00,0
4,1.705328e+09,2,100018010006603466,10001,80,10006,60346,6,-1,-1,...,20,100,0,4,870,0.000000,0.000000e+00,0.000000,0.000000e+00,0

In [50]:
df.to_csv('Dataset1.csv',index=False)